hmcts/ccpay-bubble

package.json
yarn.lock

https://github.com/hmcts/ccpay-bubble/compare/PAY-2179
```
[ ] Yes
[x] No
```

updating package json version changes

---

package.json
yarn.lock

Payment view component back link issue fixes

---

package.json
yarn.lock

removing redirection back link changes

---

infrastructure/main.tf

Fix AAT build pipeline

---

infrastructure/prod.tfvars

https://tools.hmcts.net/jira/browse/PAY-2058
Updating IDAMURL in production 
```
[ ] Yes
[x ] No
```

Updating Idam URL in production

---

infrastructure/prod.tfvars
infrastructure/variables.tf

Pointing ccd link to production

---

infrastructure/aat.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

Updated CCD URL TO Prod 
```
[ ] Yes
[ X] No
```

[[KN]]- Updated CCD URL TO Prod 

---

express/infrastructure/security.js

Logout Issue

---

charts/ccpay-bubble-frontend/values.yaml
config/default.yaml
infrastructure/main.tf
start.js

PAY-2390:MITM Attack changes

---

infrastructure/main.tf

Updated main.tf from moj to cnp

---

start.js

Revert MIMT changes

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/requirements.yaml
charts/ccpay-bubble-frontend/values.preview.template.yaml
charts/ccpay-bubble-frontend/values.yaml

Tidying up chart for product chart

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/requirements.yaml
charts/ccpay-bubble-frontend/values.preview.template.yaml

Updating idma charts version
```
[ ] Yes
[ ] No
```

Updating idam charts version

---

charts/ccpay-bubble-frontend/values.yaml
infrastructure/main.tf

Changed the Payment api urls according to standards

PAY-2419:AKS Migration Payment App

---

infrastructure/main.tf

PAY-2419:Paybubble update in teraform for health check

---

infrastructure/aat.tfvars
infrastructure/prod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PAY-2682
CCD Integration Issue: Internal URL can be accessible with HTTP only.
```
[ ] Yes
[x] No
```

Ccd live incident fixes

---

config/default.yaml
infrastructure/main.tf

Fixing bulk scan url issue
```
[ ] Yes
[x] No
```

Live issue

---

config/default.yaml

idamurlchange

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/values.yaml

fixing ingress

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/values.yaml

Chart changes

---

express/infrastructure/security.js
package.json
yarn.lock

add validation for surplus and short fall issue

---

Jenkinsfile_CNP
acceptance-tests/test/end-to-end/pages/steps_file.js
package.json
src/app/app.module.ts
src/app/components/ccd-search/ccd-search.component.html
src/app/components/ccd-search/ccd-search.component.spec.ts
src/app/components/ccd-search/ccd-search.component.ts
src/app/components/payment-history/payment-history.component.html
src/app/components/payment-history/payment-history.component.ts
yarn.lock

paybubble_enhancements
```
[ ] Yes
[ ] No
```

Paybubble enhamcements

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/values.yaml
config/custom-environment-variables.yaml
config/default.yaml
express/infrastructure/security-factory.js
express/infrastructure/security.js

Oidc demo changes

---

src/app/components/fee-search/fee-search.component.spec.ts
src/app/components/fee-search/fee-search.component.ts

System testing bug fixing

---

src/app/components/ccd-search/ccd-search.component.ts
src/app/components/fee-search/fee-search.component.ts
src/app/services/payment-group/payment-group.service.spec.ts

Frontdoor waf

---

src/app/components/ccd-search/ccd-search.component.spec.ts

AZURE RM version changes

---

package.json

Modified package.json

---

acceptance-tests/test/end-to-end/pages/steps_file.js
package.json
yarn.lock

Exception Changes

---

yarn.lock

PAY-4022 cve fixes

---

Jenkinsfile_nightly

Increased nightly timeout to 90mins for functional tests
```
[ ] Yes
[x] No
```

Nightly functional tests timeout increased to 90mins

---

acceptance-tests/test/end-to-end/helpers/misc.js
acceptance-tests/test/end-to-end/pages/case_search.js
acceptance-tests/test/end-to-end/pages/steps_file.js
acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js

https://tools.hmcts.net/jira/browse/PAY-4084
Fixing dummy test nightly failure 
```
[ ] Yes
[x] No
```

Pbnightlybuildfix

---

package.json
src/app/components/fee-details/fee-details.component.spec.ts
yarn.lock

 PAY-3521-TransactionId-display

---

Jenkinsfile_nightly

report fix
```
[ ] Yes
[x] No
```

Mutation report fix

---

Jenkinsfile_nightly
scripts/pa11y.js

Adding remaining Pa11y pages:
- Confirm association page
- Mark pay as transferred page
- Mark payment as unidentified page
```
[ ] Yes
[x] No
```

TA-490 Adding last 3 pa11y pages

---

src/app/components/fee-details/fee-details.component.spec.ts

Live issue testcasefixes

---

config/default.yaml

security fixes

---

src/app/shared/components/phase-banner/phase-banner.component.ts

vulnarability fix

---

src/app/components/fee-details/fee-details.component.spec.ts

unit test fix

---

package.json

Nightly dev

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js

modified failed functional tests

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js

modified fucntional Tests2

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
src/index.html

Test build

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/values.yaml

Pub scr key

---

Jenkinsfile_nightly

PAY-5512 - Disable cross browser test from nightly dev

---

Jenkinsfile_nightly
acceptance-tests/saucelabs.conf.js
acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
package.json

https://tools.hmcts.net/jira/browse/PAY-5512
```
[ ] Yes
[X] No
```

update cross browser tests config

---

src/app/app.component.html
src/app/app.component.ts

Merge confilct changes

---

src/app/app.component.html

enabled cookie banner

---

acceptance-tests/test/end-to-end/helpers/utils.js
acceptance-tests/test/end-to-end/pages/steps_file.js
acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js

fix functional tests

---

acceptance-tests/codecept.conf.js
acceptance-tests/test/end-to-end/helpers/misc.js
acceptance-tests/test/end-to-end/pages/case_transactions.js
acceptance-tests/test/end-to-end/tests/Payment_Failure_BounceBack_test.js

uncommenting Payment status update FE_FN tests

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js

ft suppress

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js

https://tools.hmcts.net/jira/browse/PAY-4884
Ignoring test to pass pipeline, raised ticket PAY-5982.
```
[ ] Yes
[x] No
```

Ignored test PAY-5982

---

acceptance-tests/test/end-to-end/tests/Refunds_V2_test.js

https://tools.hmcts.net/jira/browse/PAY-6080
Remove Refund tests which inconsistent. 
```
[ ] Yes
[x] No
```

PAY-6040: Remove flakey refund tests

---

Jenkinsfile_CNP
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6259
Extend timeout for unprocessed payments options to be enabled.
```
[ ] Yes
[x] No
```

PAY-6259: Update timeout.

---

.eslintignore
acceptance-tests/test/end-to-end/pages/initiate_refunds.js
acceptance-tests/test/end-to-end/pages/payment_history.js
acceptance-tests/test/end-to-end/tests/Refund_Full_Payment_Option_Selection_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Partial_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Rejected_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_SentBackToCaseworker_Journey_test.js

https://tools.hmcts.net/jira/browse/PAY-6378

Refactor and enable Refunds journey tests

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
acceptance-tests/test/end-to-end/tests/Refund_Partial_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js

https://tools.hmcts.net/jira/browse/PAY-6808

add waits to fix FT failures

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6780
Update to allow the Payment Failure Event Report to show up.

PAY-6780: Update to show Payment Failure Event report

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6817
Update web component to test Reports running.

PAY-6817: Update web-component fix Paybubble report initialisation

---

acceptance-tests/test/end-to-end/pages/reports.js

PAY-6911: Pipeline analysis and resolution 26 February 2023
[PAY-6911] (https://tools.hmcts.net/jira/browse/PAY-6911).

PAY-6911: Pipeline analysis and resolution 26 February 2023

---

acceptance-tests/test/end-to-end/pages/fees_summary.js
acceptance-tests/test/end-to-end/pages/steps_file.js
acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
express/infrastructure/security.js
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6806
Reverting change to this PR
https://github.com/hmcts/ccpay-web-component/pull/341

PAY-6806: Reverting change.

---

acceptance-tests/test/end-to-end/pages/initiate_refunds.js
acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js

PAY-6761: Continue on retro remission screen enabled/disabled
   [PAY-6761] (https://tools.hmcts.net/jira/browse/PAY-6761).

 PAY-6948: ccpay-bubble functional test failure

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6945
Fix inconsisitencies with PBA payment button fix.

PBA Button fix web-component update,

---

.github/workflows/stale.yml
charts/ccpay-bubble-frontend/Chart.yaml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Node version update and PR Close autobot stale file addition
- [ x ] Does this PR introduce a breaking change

Pay 6982 Node version update and PR Close autobot stale file addition

---

.github/workflows/stale.yml
charts/ccpay-bubble-frontend/Chart.yaml

https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Node version update and stale.yml file added for PR Auto-close bot
- [ x ] Does this PR introduce a breaking change

PAY-6982 Node version update and auto close bot for PR

---

acceptance-tests/test/end-to-end/pages/add_fees.js
projects/fee-register-search/src/lib/components/fee-list/fee-list.component.html
projects/fee-register-search/src/lib/components/fee-list/fee-list.component.scss
projects/fee-register-search/src/lib/components/fee-list/fee-list.component.spec.ts
projects/fee-register-search/src/lib/components/fee-list/fee-list.component.ts

https://tools.hmcts.net/jira/browse/PAY-6931
Add column for jurisdiction 2

PAY-6931 Add column for jurisdiction 2

---

package.json
yarn.lock

[### Jira link (if applicable)](https://tools.hmcts.net/jira/browse/PAY-7031)
- [ x ] commit messages are meaningful and follow good commit message guidelines

updates version for web-component hotfix

---

acceptance-tests/test/end-to-end/pages/add_fees.js
acceptance-tests/test/end-to-end/pages/steps_file.js
acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
acceptance-tests/test/end-to-end/tests/Refund_Full_Payment_Option_Selection_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Rejected_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
acceptance-tests/test/end-to-end/tests/Refund_SentBackToCaseworker_Journey_test.js

https://tools.hmcts.net/jira/browse/PAY-7041

Fix FTs as per new fee changes

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6748
Critical CVE found with update of footers.

Critical CVE fix.

---

acceptance-tests/codecept.conf.js
acceptance-tests/test/end-to-end/tests/CCPBAcceptanceTestConstants.js
charts/ccpay-bubble-frontend/values.aat.template.yaml
charts/ccpay-bubble-frontend/values.preview.template.yaml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-7232
Improve reliability of Paybubble FT

PAY--7232: Improve reliability of Paybubble FT

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-6837
Changed web component verion to 6.2.2

PAY-6837 updated yarn.lock file and web component version 6.2.2

---

audit.json

https://tools.hmcts.net/jira/browse/PAY-7244
Fix for Paybubble security scan - suppressing these issues as they are related to non-usable requests.

PAY-7244: Pipeline fix

---

acceptance-tests/test/end-to-end/helpers/utils.js
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-7120
to address VUL-6113

PAY-7120 updated yarn.lock file and web component version 6.2.5-beta01

---

express/infrastructure/health-info.js

https://tools.hmcts.net/jira/browse/PAY-7317
Removed S2S and IdAM health checks as part of the health check endpoint.
Checked application is healthy.

PAY-7317: Remove uncessary health checks

---

yarn-audit-known-issues

See [PAY-7347](https://tools.hmcts.net/jira/browse/PAY-7347)
Not needed suppression as stated in build.
Rebuilt on nightly-dev branch

PAY-7347 rerun know-issues for vulnerabilities

---

server.js

PAY-7365: Pipeline fixes - week beginning 23nd October 2024
[PAY-7365] (https://tools.hmcts.net/jira/browse/PAY-7365).

Pay 7365 new pass

---

audit.json

PAY-7365: Pipeline fixes - week beginning 23nd October 2024
[PAY-7365] (https://tools.hmcts.net/jira/browse/PAY-7365).

PAY-7365: Pipeline fixes - week beginning 23nd October 2024

---

acceptance-tests/test/end-to-end/pages/steps_file.js
acceptance-tests/test/end-to-end/tests/CCPB_Probate.js
acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js

https://tools.hmcts.net/jira/browse/PAY-7434

update FTs to use probate cases

---

charts/ccpay-bubble-frontend/Chart.yaml
charts/ccpay-bubble-frontend/values.yaml

https://tools.hmcts.net/jira/browse/CME-8
Cleanup since settings are now in cnp-flux-config.
https://github.com/hmcts/cnp-flux-config/pull/35279
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-8: Update values.yaml

---

package.json
yarn.lock

PAY-7470: Pipeline fixes - week beginning 18 Nov 2024
[PAY-7470] (https://tools.hmcts.net/jira/browse/PAY-7470).

  PAY-7470: Pipeline fixes - week beginning 18 Nov 2024

---

acceptance-tests/test/end-to-end/pages/payment_history.js

https://tools.hmcts.net/jira/browse/PAY-7522
Add dynamic year check in test.
FT issue.

PAY-7522: Fix full year check in functional test

---

package.json
yarn.lock

See [PAY-7643](https://tools.hmcts.net/jira/browse/PAY-7643)
Web-component version change
Created web-component and changed the version.  Referenced the version in pay-bubble, compiled and ran application.  All working with no errors

PAY-7643 version for web-component changed

---

charts/ccpay-bubble-frontend/Chart.yaml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/CME-413
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-413: Update pa11y, nodejs and OCI endpoint

---

acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js

https://tools.hmcts.net/jira/browse/PAY-7740
Inflation update, so tests require updating.
FT should pass.

PAY-7740: Fix functional tests after inflation update

---

express/services/PayhubService.js

https://tools.hmcts.net/jira/browse/PAY-7981
Payment App request for report generation was returning a string instead of JSON.
Tested locally.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

PAY-7981: Correct report to return JSON

---

acceptance-tests/test/end-to-end/helpers/utils.js
acceptance-tests/test/end-to-end/pages/add_fees.js
acceptance-tests/test/end-to-end/pages/confirm_association.js
acceptance-tests/test/end-to-end/pages/fees_summary.js
acceptance-tests/test/end-to-end/pages/paybubble_static_data.js
acceptance-tests/test/end-to-end/tests/Payment_Failure_BounceBack_test.js
acceptance-tests/test/end-to-end/tests/Refund_Remissions_Multiple_SRs_test.js

https://tools.hmcts.net/jira/browse/PAY-8017

add multiple SRs remission refund test
